crypto: gate ticketer module on std for aws-lc-rs
Fixes a missing import error when building without std and with
aws_lc_rs:
```
$ cargo check -p rustls --no-default-features --features aws_lc_rs
   Compiling rustls v0.23.0 (/home/daniel/Code/Rust/rustls/rustls)
error[E0432]: unresolved import `ticketer`
   --> rustls/src/crypto/aws_lc_rs/mod.rs:228:9
    |
228 | pub use ticketer::Ticketer;
    |         ^^^^^^^^ use of undeclared crate or module `ticketer`
```

Adding a `std` gate on `TICKETER_AEAD` was also required to fix unused
warnings for builds w/o `std` using either ring or aws_lc_rs:

```
$ cargo check -p rustls --no-default-features --features aws_lc_rs
   Compiling rustls v0.23.0 (/home/daniel/Code/Rust/rustls/rustls)
warning: static `TICKETER_AEAD` is never used
   --> rustls/src/crypto/aws_lc_rs/mod.rs:249:19
    |
249 | pub(super) static TICKETER_AEAD: &ring_like::aead::Algorithm = &ring_like::aead::AES_256_GCM;
    |                   ^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default
```