Fix minimal versions job
This is mysterious:

```
error: failed to select a version for `log`.
    ... required by package `env_logger v0.10.0`
    ... which satisfies dependency `env_logger = "^0.10"` of package `bogo v0.1.0 (/home/jbp/src/rustls/bogo)`
versions that meet the requirements `^0.4.8` are: 0.4.22, 0.4.21, 0.4.20, 0.4.19, 0.4.18, 0.4.17, 0.4.16, 0.4.15, 0.4.14, 0.4.13, 0.4.11, 0.4.8

all possible versions conflict with previously selected packages.

  previously selected package `log v0.4.4`
    ... which satisfies dependency `log = "^0.4.4"` of package `rustls v0.23.12 (/home/jbp/src/rustls/rustls)`
    ... which satisfies path dependency `rustls` of package `bogo v0.1.0 (/home/jbp/src/rustls/bogo)`

failed to select a version for `log` which could resolve this conflict
error: process didn't exit successfully: `rustup run nightly cargo update -Z direct-minimal-versions` (exit status: 101)
```

First, why is the `bogo` crate even being considered?  This
command is purposefully run in `rustls/` and no other workspace
members should be involved.

Second, why is 0.4.4 not considered?  That is because `env_logger==0.10.0`
requires ^0.4.8.

Third, why is it important that the minimal version of `env_logger` wants something
later than our specified minimal version?  `direct-minimal-versions` should
be the opposite of caring about the versions specified by second-order dependencies.