examples: fix no logging feature usage.
Previously the `tlsserver-mio.rs` example unconditionally used `extern
crate log`, causing errors of the following form to be emitted when
building examples without the "logging" feature enabled:

```
error[E0658]: use of unstable library feature 'rustc_private': this
crate is being loaded from the sysroot, an unstable location; did you
mean to load this crate from crates.io via `Cargo.toml` instead?
 --> examples/src/bin/tlsserver-mio.rs:6:1
  |
6 | extern crate log;
  | ^^^^^^^^^^^^^^^^^
  |
```

This commit resolves the breakage, allowing building the examples
without logging. To do two of the the log macro shims from rustls/lib.rs
are duplicated for use from the example code for this situation. Once
fixed, a couple of new clippy findings are addressed for the case where
no logging support is enabled and some variables thus appear "unused".