error: use UnknownCA alert for Error:UnknownRevocationStatus
This matches OpenSSL, BoringSSL and AWS-LC. Since the existing
functionality was heavily referencing these projects it seems sensible
to do the same here.